In [1]:
import pandas as pd

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pwd

'C:\\Users\\reddyvari.n\\Downloads\\Algorithms_practiced\\Linear Regression'

In [3]:
cd C:\\Users\\reddyvari.n\\Downloads\\Ashok\

[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\reddyvari.n\\\\Downloads\\\\Ashok'
C:\Users\reddyvari.n\Downloads\Algorithms_practiced\Linear Regression


In [4]:
df=pd.read_csv("Salary_Data.csv")

NameError: name 'pd' is not defined

In [ ]:
df

In [ ]:
x=df.iloc[:,:-1].values

In [ ]:
y=df.iloc[:,1].values

In [ ]:
y

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
ytrain

In [ ]:
from sklearn.linear_model import Laso

In [34]:
lr=LinearRegression()

In [37]:
lr.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [38]:
ypredict=lr.predict(xtest)

In [39]:
ypredict

array([ 40748.96184072, 122699.62295594,  64961.65717022,  63099.14214487,
       115249.56285456, 107799.50275317])

In [62]:
y=ypredict.round(decimals=0)

In [69]:
ytest,y

(array([ 37731., 122391.,  57081.,  63218., 116969., 109431.]),
 array([ 40749., 122700.,  64962.,  63099., 115250., 107800.]))

In [70]:
from sklearn.metrics import r2_score

In [71]:
from sklearn.metrics import mean_squared_error

In [72]:
print(r2_score(ytest,y))

0.9881690890084247


In [73]:
rmse=np.sqrt(mean_squared_error(ytest,y))

In [74]:
rmse

3581.0438189630318