In [8]:
import pandas as pd
import numpy as np

In [9]:
cd C:\\Users\\reddyvari.n\\Downloads\\Ashok

C:\Users\reddyvari.n\Downloads\Ashok


In [6]:
df=pd.read_csv("mnist_train.csv")

In [7]:
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    28x19  \
0          5    0    0    0    0    0    0    0    0    0  ...        0   
1          0    0    0    0    0    0    0    0    0    0  ...        0   
2          4    0    0    0    0    0    0    0    0    0  ...        0   
3          1    0    0    0    0    0    0    0    0    0  ...        0   
4          9    0    0    0    0    0    0    0    0    0  ...        0   
5          2    0    0    0    0    0    0    0    0    0  ...        0   
6          1    0    0    0    0    0    0    0    0    0  ...        0   
7          3    0    0    0    0    0    0    0    0    0  ...        0   
8          1    0    0    0    0    0    0    0    0    0  ...        0   
9          4    0    0    0    0    0    0    0    0    0  ...        0   
10         3    0    0    0    0    0    0    0    0    0  ...        0   
11         5    0    0    0    0    0    0    0    0    0  ...        0   
12         3    0    0    0    0    0    0    0    0    0  ...        0   
13         6    0    0    0    0    0    0    0    0    0  ...        0   
14         1    0    0    0    0    0    0    0    0    0  ...        0   
15         7    0    0    0    0    0    0    0    0    0  ...        0   
16         2    0    0    0    0    0    0    0    0    0  ...        0   
17         8    0    0    0    0    0    0    0    0    0  ...        0   
18         6    0    0    0    0    0    0    0    0    0  ...        0   
19         9    0    0    0    0    0    0    0    0    0  ...        0   
20         4    0    0    0    0    0    0    0    0    0  ...        0   
21         0    0    0    0    0    0    0    0    0    0  ...        0   
22         9    0    0    0    0    0    0    0    0    0  ...        0   
23         1    0    0    0    0    0    0    0    0    0  ...        0   
24         1    0    0    0    0    0    0    0    0    0  ...        0   
25         2    0    0    0    0    0    0    0    0    0  ...        0   
26         4    0    0    0    0    0    0    0    0    0  ...        0   
27         3    0    0    0    0    0    0    0    0    0  ...        0   
28         2    0    0    0    0    0    0    0    0    0  ...        0   
29         7    0    0    0    0    0    0    0    0    0  ...        0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...   
59970      2    0    0    0    0    0    0    0    0    0  ...        0   
59971      2    0    0    0    0    0    0    0    0    0  ...        0   
59972      0    0    0    0    0    0    0    0    0    0  ...        0   
59973      9    0    0    0    0    0    0    0    0    0  ...        0   
59974      2    0    0    0    0    0    0    0    0    0  ...        0   
59975      4    0    0    0    0    0    0    0    0    0  ...        0   
59976      6    0    0    0    0    0    0    0    0    0  ...        0   
59977      7    0    0    0    0    0    0    0    0    0  ...        0   
59978      3    0    0    0    0    0    0    0    0    0  ...        0   
59979      1    0    0    0    0    0    0    0    0    0  ...        0   
59980      3    0    0    0    0    0    0    0    0    0  ...        0   
59981      6    0    0    0    0    0    0    0    0    0  ...        0   
59982      6    0    0    0    0    0    0    0    0    0  ...        0   
59983      2    0    0    0    0    0    0    0    0    0  ...        0   
59984      1    0    0    0    0    0    0    0    0    0  ...        0   
59985      2    0    0    0    0    0    0    0    0    0  ...        0   
59986      6    0    0    0    0    0    0    0    0    0  ...        0   
59987      0    0    0    0    0    0    0    0    0    0  ...        0   
59988      7    0    0    0    0    0    0    0    0    0  ...        0   
59989      8    0    0    0    0    0    0    0    0    0  ...        0   
59990      9    0    0    0    0    0    0    0    0    0  ...        0   
59991      2    0    0    0    0

In [10]:
x=df.iloc[:,1:]

In [15]:
y=df.iloc[:,0]

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=9)

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
r=RandomForestClassifier(n_estimators=10)
r.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [23]:
ypredict=r.predict(xtest)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [27]:
accuracy_score(ypredict,ytest)

0.9435833333333333

In [28]:
c=confusion_matrix(ypredict,ytest)

In [29]:
c

array([[1134,    1,    7,    2,    2,   12,   11,    3,    4,    5],
       [   0, 1385,    8,    6,    0,    3,    2,    7,    8,    4],
       [   2,    5, 1102,   29,   10,    3,    2,   15,   25,    2],
       [   4,    3,    7, 1110,    2,   31,    3,    3,   27,   17],
       [   1,    4,    2,    0, 1099,    3,    5,    8,   15,   28],
       [   1,    0,    4,   24,    4, 1007,   14,    0,   20,    6],
       [   5,    2,    2,    3,    8,    8, 1144,    0,   11,    4],
       [   0,    1,    9,   19,    4,    5,    0, 1218,    5,   19],
       [  13,    1,    7,   19,    9,    7,    7,    5, 1037,   12],
       [   1,    2,    2,    7,   25,    7,    1,   14,   19, 1087]],
      dtype=int64)

In [40]:
from sklearn.decomposition import PCA

In [64]:
p=PCA(n_components=10)
x1=p.fit(x).transform(x)

In [67]:
x1

array([[ 123.93259077, -312.67431503,  -24.51409065, ...,  159.78188591,
        -363.37050335,  198.15669413],
       [1011.7183793 , -294.85704453,  596.33959678, ..., -104.97819323,
          40.49265206,  150.77151636],
       [ -51.84963102,  392.17324022, -188.51020744, ...,  368.41811029,
        -114.78983035, -178.14557769],
       ...,
       [-178.05341673,  160.07813577, -257.61235108, ..., -184.51478978,
         -87.27215877,  268.00759481],
       [ 130.60609303,   -5.59197156,  513.85913542, ...,  140.89207969,
         -16.36013141,  -93.995452  ],
       [-173.43593589,  -24.71889904,  556.01914384, ..., -154.3950869 ,
          87.47312204, -121.28192239]])

In [68]:
p.explained_variance_ratio_

array([0.09704664, 0.07095924, 0.06169089, 0.05389419, 0.04868797,
       0.04312231, 0.0327193 , 0.02883892, 0.02762027, 0.02356996])

In [69]:
p.components_[1]

array([ 1.67467650e-17, -1.36569363e-17,  8.88865742e-18, -4.79135450e-19,
        1.32028660e-18, -3.26472838e-19, -3.17338156e-20, -2.85423928e-20,
       -2.88465593e-21, -3.00740245e-21, -9.59534343e-23, -9.13169247e-22,
        1.79705769e-06,  6.03015451e-06,  2.33157659e-06,  9.71490246e-08,
        2.57058746e-23,  1.44556998e-23, -3.03467610e-24, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        3.35955312e-07,  1.39787198e-06,  2.59839326e-05,  6.07773217e-05,
        6.49179891e-05,  8.59164181e-05,  1.75752349e-04,  2.50796610e-04,
        2.84670164e-04,  2.45602630e-04,  2.16196938e-04,  1.77666567e-04,
        1.66311060e-04,  1.38803879e-04,  8.08573008e-05,  2.46545775e-05,
        5.09013123e-06,  3.85765094e-06,  9.18798031e-06,  7.18279665e-06,
       -0.00000000e+00, -

In [70]:
df1

array([[ 123.9325177 , -312.68533974],
       [1011.71851475, -294.85773239],
       [ -51.84966536,  392.17380996],
       ...,
       [-178.05356179,  160.07508272],
       [ 130.60606813,   -5.59785968],
       [-173.4360998 ,  -24.70725546]])

In [71]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x1,y,test_size=0.2,random_state=9)

In [72]:
r1=RandomForestClassifier()
r1.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [73]:
ypredict=r1.predict(xtest)

In [74]:
accuracy_score(ypredict,ytest)

0.8899166666666667