In [8]:
import pandas as pd
import numpy as np

In [9]:
cd C:\\Users\\reddyvari.n\\Downloads\\Ashok

C:\Users\reddyvari.n\Downloads\Ashok


In [6]:
df=pd.read_csv("mnist_train.csv")

In [7]:
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    28x19  \
0          5    0    0    0    0    0    0    0    0    0  ...        0   
1          0    0    0    0    0    0    0    0    0    0  ...        0   
2          4    0    0    0    0    0    0    0    0    0  ...        0   
3          1    0    0    0    0    0    0    0    0    0  ...        0   
4          9    0    0    0    0    0    0    0    0    0  ...        0   
5          2    0    0    0    0    0    0    0    0    0  ...        0   
6          1    0    0    0    0    0    0    0    0    0  ...        0   
7          3    0    0    0    0    0    0    0    0    0  ...        0   
8          1    0    0    0    0    0    0    0    0    0  ...        0   
9          4    0    0    0    0    0    0    0    0    0  ...        0   
10         3    0    0    0    0    0    0    0    0    0  ...        0   
11         5    0    0    0    0    0    0    0    0    0  ...        0   
12         3    0    0    0    0    0    0    0    0    0  ...        0   
13         6    0    0    0    0    0    0    0    0    0  ...        0   
14         1    0    0    0    0    0    0    0    0    0  ...        0   
15         7    0    0    0    0    0    0    0    0    0  ...        0   
16         2    0    0    0    0    0    0    0    0    0  ...        0   
17         8    0    0    0    0    0    0    0    0    0  ...        0   
18         6    0    0    0    0    0    0    0    0    0  ...        0   
19         9    0    0    0    0    0    0    0    0    0  ...        0   
20         4    0    0    0    0    0    0    0    0    0  ...        0   
21         0    0    0    0    0    0    0    0    0    0  ...        0   
22         9    0    0    0    0    0    0    0    0    0  ...        0   
23         1    0    0    0    0    0    0    0    0    0  ...        0   
24         1    0    0    0    0    0    0    0    0    0  ...        0   
25         2    0    0    0    0    0    0    0    0    0  ...        0   
26         4    0    0    0    0    0    0    0    0    0  ...        0   
27         3    0    0    0    0    0    0    0    0    0  ...        0   
28         2    0    0    0    0    0    0    0    0    0  ...        0   
29         7    0    0    0    0    0    0    0    0    0  ...        0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...   
59970      2    0    0    0    0    0    0    0    0    0  ...        0   
59971      2    0    0    0    0    0    0    0    0    0  ...        0   
59972      0    0    0    0    0    0    0    0    0    0  ...        0   
59973      9    0    0    0    0    0    0    0    0    0  ...        0   
59974      2    0    0    0    0    0    0    0    0    0  ...        0   
59975      4    0    0    0    0    0    0    0    0    0  ...        0   
59976      6    0    0    0    0    0    0    0    0    0  ...        0   
59977      7    0    0    0    0    0    0    0    0    0  ...        0   
59978      3    0    0    0    0    0    0    0    0    0  ...        0   
59979      1    0    0    0    0    0    0    0    0    0  ...        0   
59980      3    0    0    0    0    0    0    0    0    0  ...        0   
59981      6    0    0    0    0    0    0    0    0    0  ...        0   
59982      6    0    0    0    0    0    0    0    0    0  ...        0   
59983      2    0    0    0    0    0    0    0    0    0  ...        0   
59984      1    0    0    0    0    0    0    0    0    0  ...        0   
59985      2    0    0    0    0    0    0    0    0    0  ...        0   
59986      6    0    0    0    0    0    0    0    0    0  ...        0   
59987      0    0    0    0    0    0    0    0    0    0  ...        0   
59988      7    0    0    0    0    0    0    0    0    0  ...        0   
59989      8    0    0    0    0    0    0    0    0    0  ...        0   
59990      9    0    0    0    0    0    0    0    0    0  ...        0   
59991      2    0    0    0    0

In [10]:
x=df.iloc[:,1:]

In [15]:
y=df.iloc[:,0]

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=9)

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
r=RandomForestClassifier(n_estimators=10)
r.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [23]:
ypredict=r.predict(xtest)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [27]:
accuracy_score(ypredict,ytest)

0.9435833333333333

In [28]:
c=confusion_matrix(ypredict,ytest)

In [29]:
c

array([[1134,    1,    7,    2,    2,   12,   11,    3,    4,    5],
       [   0, 1385,    8,    6,    0,    3,    2,    7,    8,    4],
       [   2,    5, 1102,   29,   10,    3,    2,   15,   25,    2],
       [   4,    3,    7, 1110,    2,   31,    3,    3,   27,   17],
       [   1,    4,    2,    0, 1099,    3,    5,    8,   15,   28],
       [   1,    0,    4,   24,    4, 1007,   14,    0,   20,    6],
       [   5,    2,    2,    3,    8,    8, 1144,    0,   11,    4],
       [   0,    1,    9,   19,    4,    5,    0, 1218,    5,   19],
       [  13,    1,    7,   19,    9,    7,    7,    5, 1037,   12],
       [   1,    2,    2,    7,   25,    7,    1,   14,   19, 1087]],
      dtype=int64)

In [40]:
from sklearn.decomposition import PCA

In [75]:
p=PCA(n_components=20)
x1=p.fit(x).transform(x)

In [76]:
x1

array([[ 123.93258874, -312.67426192,  -24.51404771, ...,  309.21694547,
         277.33647089,  177.35195932],
       [1011.71837587, -294.85703744,  596.33957206, ...,   40.1960273 ,
          57.55175317,  -88.42742096],
       [ -51.8496079 ,  392.17315322, -188.50974476, ..., -121.9693675 ,
          -5.38506369, -435.7123882 ],
       ...,
       [-178.05344953,  160.07820944, -257.61309982, ...,  -38.52953628,
          93.49684402,  225.64968994],
       [ 130.60607214,   -5.59193647,  513.85867475, ..., -142.26207282,
         -79.37987958,  199.5588426 ],
       [-173.43595233,  -24.7188041 ,  556.01887388, ...,  268.51665752,
          93.9021198 , -216.78798132]])

In [77]:
p.explained_variance_ratio_

array([0.09704664, 0.07095924, 0.06169089, 0.05389419, 0.04868797,
       0.04312231, 0.0327193 , 0.02883895, 0.02762029, 0.02357   ,
       0.02109189, 0.02022991, 0.01715817, 0.01692107, 0.01578639,
       0.01482886, 0.01324516, 0.01276856, 0.01187023, 0.01151455])

In [78]:
p.components_[1]

array([ 1.03132794e-16, -1.74192026e-17, -2.87545316e-18,  3.43794452e-18,
        2.34366002e-20,  8.94893779e-20, -7.48874847e-20, -8.02496958e-20,
       -1.56787317e-20,  4.99094768e-20, -3.43230526e-22,  3.06247686e-22,
        1.79705989e-06,  6.03016363e-06,  2.33158137e-06,  9.71492238e-08,
       -8.60436185e-23, -8.85827242e-23, -6.22543921e-23,  5.77142958e-24,
        2.55004751e-24,  7.62064065e-24,  2.91277939e-24,  1.90229709e-24,
       -8.08393898e-26,  1.18481130e-25,  5.90889004e-25,  1.20680659e-24,
       -1.99958278e-25,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        3.35956322e-07,  1.39787513e-06,  2.59839463e-05,  6.07773598e-05,
        6.49180514e-05,  8.59165285e-05,  1.75752605e-04,  2.50796993e-04,
        2.84670612e-04,  2.45603100e-04,  2.16197412e-04,  1.77666935e-04,
        1.66311324e-04,  1.38804020e-04,  8.08573656e-05,  2.46546407e-05,
        5.09019619e-06,  3.85768405e-06,  9.18800217e-06,  7.18280697e-06,
        0.00000000e+00,  

In [79]:
df1

array([[ 123.9325177 , -312.68533974],
       [1011.71851475, -294.85773239],
       [ -51.84966536,  392.17380996],
       ...,
       [-178.05356179,  160.07508272],
       [ 130.60606813,   -5.59785968],
       [-173.4360998 ,  -24.70725546]])

In [80]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x1,y,test_size=0.2,random_state=9)

In [82]:
r1=RandomForestClassifier()
r1.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [83]:
ypredict=r1.predict(xtest)

In [84]:
accuracy_score(ypredict,ytest)

0.9236666666666666