#  Naive Bayes Classifiers

In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectPercentile, f_classif

## Naive Bayes
### Using Naive Bayes to predict spam

In [3]:
#Use Latin encoding as the Data has non UFT-8 Chars
data = pd.read_csv("spam.csv",encoding='latin-1')

In [14]:
data.shape

(5572, 5)

In [36]:
data[data.v1=='spam']


v1                                                 v2    Unnamed: 2  \
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...           NaN   
5     spam  FreeMsg Hey there darling it's been 3 week's n...           NaN   
8     spam  WINNER!! As a valued network customer you have...           NaN   
9     spam  Had your mobile 11 months or more? U R entitle...           NaN   
11    spam  SIX chances to win CASH! From 100 to 20,000 po...           NaN   
12    spam  URGENT! You have won a 1 week FREE membership ...           NaN   
15    spam  XXXMobileMovieClub: To use your credit, click ...           NaN   
19    spam  England v Macedonia - dont miss the goals/team...           NaN   
34    spam  Thanks for your subscription to Ringtone UK yo...           NaN   
42    spam  07732584351 - Rodger Burns - MSG = We tried to...           NaN   
54    spam  SMS. ac Sptv: The New Jersey Devils and the De...           NaN   
56    spam  Congrats! 1 year special cinema pass for 2 is ...           NaN   
65    spam  As a valued customer, I am pleased to advise y...           NaN   
67    spam  Urgent UR awarded a complimentary trip to Euro...           NaN   
68    spam  Did you hear about the new \Divorce Barbie\"? ...           NaN   
93    spam  Please call our customer service representativ...           NaN   
95    spam  Your free ringtone is waiting to be collected....   PO Box 5249   
113   spam  GENT! We are trying to contact you. Last weeke...           NaN   
116   spam  You are a winner U have been specially selecte...           NaN   
119   spam  PRIVATE! Your 2004 Account Statement for 07742...           NaN   
120   spam  URGENT! Your Mobile No. was awarded å£2000 Bon...           NaN   
122   spam  Todays Voda numbers ending 7548 are selected t...           NaN   
133   spam  Sunshine Quiz Wkly Q! Win a top Sony DVD playe...           NaN   
134   spam  Want 2 get laid tonight? Want real Dogging loc...           NaN   
138   spam  You'll not rcv any more msgs from the chat svc...           NaN   
146   spam  FreeMsg Why haven't you replied to my text? I'...           NaN   
158   spam  Customer service annoncement. You have a New Y...           NaN   
159   spam  You are a winner U have been specially selecte...           NaN   
163   spam  -PLS STOP bootydelious (32/F) is inviting you ...           NaN   
164   spam  BangBabes Ur order is on the way. U SHOULD rec...           NaN   
...    ...                                                ...           ...   
5342  spam  u r subscribed 2 TEXTCOMP 250 wkly comp. 1st w...           NaN   
5364  spam  Call 09095350301 and send our girls into eroti...           NaN   
5365  spam  Camera - You are awarded a SiPix Digital Camer...           NaN   
5366  spam  A å£400 XMAS REWARD IS WAITING FOR YOU! Our co...           NaN   
5368  spam  IMPORTANT MESSAGE. This is a final contact att...           NaN   
5370  spam  dating:i have had two of these. Only started a...           NaN   
5377  spam  The current leading bid is 151. To pause this ...           NaN   
5378  spam  Free entry to the gr8prizes wkly comp 4 a chan...           NaN   
5381  spam         You have 1 new message. Call 0207-083-6089           NaN   
5427  spam  Santa Calling! Would your little ones like a c...           NaN   
5443  spam  You have won a guaranteed 32000 award or maybe...           NaN   
5449  spam  Latest News! Police station toilet stolen, cop...           NaN   
5456  spam  \For the most sparkling shopping breaks from 4...           NaN   
5460  spam  December only! Had your mobile 11mths+? You ar...           NaN   
5462  spam  Txt: CALL to No: 86888 & claim your reward of ...           NaN   
5466  spam  http//tms. widelive.com/index. wml?id=820554ad...           NaN   
5467  spam  Get your garden ready for summer with a FREE s...           NaN   
5468  spam  URGENT! Last weekend's draw shows that you hav...           NaN   
5482  spam  URGENT We are trying to contact you Last weeke

In [9]:
X =  data.v2
y = data.v1

In [11]:
X.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: v2, dtype: object

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [13]:
X_test.shape

(1393,)

In [15]:
vectorizer = TfidfVectorizer()

In [16]:
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_transformed  = vectorizer.transform(X_test)
feature_names = vectorizer.get_feature_names()

In [17]:
len(feature_names)

7369

In [18]:
#### slim the data for training and testing
selector = SelectPercentile( percentile=10)
selector.fit(X_train_transformed, y_train)
X_train_transformed_per = selector.transform(X_train_transformed).toarray()
X_test_transformed_per  = selector.transform(X_test_transformed).toarray()

In [21]:
X_test_transformed_per.shape

(1393, 737)

In [22]:
clf = GaussianNB()
clf.fit(X_train_transformed_per, y_train)
y_predict = clf.predict(X_test_transformed_per)

In [23]:
print(accuracy_score(y_test, y_predict))

0.9727207465900933


In [24]:
confusion_matrix(y_test, y_predict)


array([[1180,   22],
       [  16,  175]])

In [55]:
print(classification_report(y_test, y_predict))

             precision    recall  f1-score   support

        ham       0.99      0.98      0.99      1211
       spam       0.89      0.91      0.90       182

avg / total       0.97      0.97      0.97      1393



In [39]:
NewEmail = pd.Series(["Urgent UR awarded a complimentary trip"])
NewEmail


0    Urgent UR awarded a complimentary trip
dtype: object

In [40]:
NewEmail_transformed = vectorizer.transform(NewEmail)
NewEmail_transformed  = selector.transform(NewEmail_transformed).toarray()
clf.predict(NewEmail_transformed)

array(['spam'], dtype='<U4')

In [76]:
clf_mul = MultinomialNB()
clf_mul.fit(X_train_transformed_per, y_train)
y_predict_mul = clf_mul.predict(X_test_transformed_per)

In [77]:
confusion_matrix(y_test, y_predict_mul)


array([[1211,    0],
       [  54,  128]])

In [78]:
accuracy_score(y_test, y_predict_mul)

0.9612347451543432

In [79]:
clf_ber = BernoulliNB()
clf_ber.fit(X_train_transformed_per, y_train)
y_predict_ber = clf_ber.predict(X_test_transformed_per)

In [80]:
accuracy_score(y_test, y_predict_ber)

0.9842067480258435

In [81]:
confusion_matrix(y_test, y_predict_ber)

array([[1208,    3],
       [  19,  163]])