In [4]:
import pandas as pd
import numpy as np

In [5]:
dates=pd.date_range('2013-01-01',periods=6)

In [6]:
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))

In [7]:
df

A         B         C         D
2013-01-01 -0.242266 -0.364759 -2.354162  0.594034
2013-01-02  0.791215 -1.598101  1.407605 -0.289896
2013-01-03 -0.432507 -0.149483 -0.035711  1.832488
2013-01-04 -0.243125  1.117400 -0.313730  1.076543
2013-01-05 -0.624850  0.185416  0.418908  0.342160
2013-01-06 -1.112051  1.620804  2.116970  2.642378

In [8]:
import random
r=random.random()

In [9]:
r

0.05933054471447652

In [10]:
np.random.randn(1,10)

array([[ 0.78326531, -1.89749771,  0.98035181, -0.4969522 , -0.47465402,
         0.14602003,  0.6110432 ,  0.14961591,  0.59480633, -0.70085854]])

In [11]:
np.random.random(5)

array([0.14900919, 0.60262338, 0.41178745, 0.12121309, 0.39438114])

In [12]:
np.random.normal(10)

8.287647122913084

In [13]:
np.random.normal(size=5)

array([-1.45918853, -0.282004  ,  0.42211887,  0.44577592,  0.31928365])

In [14]:
np.random.randint(low=1,high=100,size=100)

array([45, 64, 14,  1, 52, 41, 40, 67,  1, 32, 58, 69, 79, 37, 63, 62, 86,
       68,  7, 38, 22, 68, 29,  7, 68, 14, 77, 31, 14, 19, 62, 28, 75, 39,
       41, 81, 36, 18, 92, 23, 69, 91, 88, 69,  2, 64, 99, 71, 36, 93, 45,
       39, 56, 39,  7, 25, 96, 59,  9, 51, 49, 73, 46, 70, 12, 66, 34, 52,
       82, 84, 42, 80, 31, 49, 87, 81,  3, 72, 37, 17, 10, 72, 48, 20, 46,
       90, 23,  7,  2, 31, 48, 37, 78, 25, 49, 29, 86, 29, 74, 60])

In [15]:
data1=[1,4,6,7,89,6788,8]

In [16]:
data2=[4,8,56,78,34,67,88]

In [21]:
pd.merge(data1,data2)

pd.merge(data1,data2)
