In [3]:
import pandas as pd
import numpy as np

In [5]:
cd C:\Users\reddyvari.n\Downloads\Ashok

C:\Users\reddyvari.n\Downloads\Ashok


In [7]:
df=pd.read_csv("spambase.txt")

In [67]:
df.shape

(4600, 58)

In [72]:
x=df.iloc[:,0:58]

In [76]:
y=df.iloc[:,-1]

In [77]:
from sklearn.decomposition import PCA

In [88]:
pca=PCA(n_components=2)
x=pca.fit_transform(x)
x

array([[ 742.63138309,  -73.99919363],
       [2019.85333496,  102.07915036],
       [ -93.04903999,    3.01079663],
       ...,
       [-170.64470978,  -18.62776421],
       [-210.27015179,  -13.0824856 ],
       [-247.75585082,   -6.84931535]])

In [94]:
pca.components_[1]

array([0., 1.])

In [95]:
pd.DataFrame(pca.explained_variance_ratio_)

0
0  0.92882
1  0.07118

In [101]:
from sklearn.model_selection import train_test_split

In [102]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [103]:
from sklearn.naive_bayes import BernoulliNB

In [105]:
b=BernoulliNB()
b.fit(xtrain,ytrain)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [106]:
ypredict=b.predict(xtest)

In [110]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [111]:
c=confusion_matrix(ypredict,ytest)

In [112]:
c

array([[386, 127],
       [152, 255]], dtype=int64)

In [113]:
accuracy_score(ypredict,ytest)

0.6967391304347826