In [111]:
import pandas as pd
import numpy as np

In [112]:
df=pd.read_csv("smsspam.txt",sep='\t',names=['Response','Actualmessage'])

In [113]:
df

Response                                      Actualmessage
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
5        spam  FreeMsg Hey there darling it's been 3 week's n...
6         ham  Even my brother is not like to speak with me. ...
7         ham  As per your request 'Melle Melle (Oru Minnamin...
8        spam  WINNER!! As a valued network customer you have...
9        spam  Had your mobile 11 months or more? U R entitle...
10        ham  I'm gonna be home soon and i don't want to tal...
11       spam  SIX chances to win CASH! From 100 to 20,000 po...
12       spam  URGENT! You have won a 1 week FREE membership ...
13        ham  I've been searching for the right words to tha...
14        ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15       spam  XXXMobileMovieClub: To use your credit, click ...
16        ham                         Oh k...i'm watching here:)
17        ham  Eh u remember how 2 spell his name... Yes i di...
18        ham  Fine if that’s the way u feel. That’s the way ...
19       spam  England v Macedonia - dont miss the goals/team...
20        ham          Is that seriously how you spell his name?
21        ham    I‘m going to try for 2 months ha ha only joking
22        ham  So ü pay first lar... Then when is da stock co...
23        ham  Aft i finish my lunch then i go str down lor. ...
24        ham  Ffffffffff. Alright no way I can meet up with ...
25        ham  Just forced myself to eat a slice. I'm really ...
26        ham                     Lol your always so convincing.
27        ham  Did you catch the bus ? Are you frying an egg ...
28        ham  I'm back &amp; we're packing the car now, I'll...
29        ham  Ahhh. Work. I vaguely remember that! What does...
...       ...                                                ...
5542      ham           Armand says get your ass over to epsilon
5543      ham             U still havent got urself a jacket ah?
5544      ham  I'm taking derek &amp; taylor to walmart, if I...
5545      ham      Hi its in durban are you still on this number
5546      ham         Ic. There are a lotta childporn cars then.
5547     spam  Had your contract mobile 11 Mnths? Latest Moto...
5548      ham                 No, I was trying it all weekend ;V
5549      ham  You know, wot people wear. T shirts, jumpers, ...
5550      ham        Cool, what time you think you can get here?
5551      ham  Wen did you get so spiritual and deep. That's ...
5552      ham  Have a safe trip to Nigeria. Wish you happines...
5553      ham                        Hahaha..use your brain dear
5554      ham  Well keep in mind I've only got enough gas for...
5555      ham  Yeh. Indians was nice. Tho it did kane me off ...
5556      ham  Yes i have. So that's why u texted. Pshew...mi...
5557      ham  No. I meant the calculation is the same. That ...
5558      ham                             Sorry, I'll call later
5559      ham  if you aren't here in the next  &lt;#&gt;  hou...
5560      ham                  Anything lor. Juz both of us lor.
5561      ham  Get me out of this dump heap. My mom decided t...
5562      ham  Ok lor... Sony ericsson salesman... I ask shuh...
5563      ham                                Ard 6 like dat lor.
5564      ham  Why don't you wait 'til at least wednesday to ...
5565      ham                                       Huh y lei...
5566     spam  REMINDER FROM O2: To get 2.50 pounds free call...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Ro

In [114]:
df.loc[df['Response']=='ham','Response']=1

In [115]:
df.loc[df['Response']=='spam','Response']=0

In [116]:
y=df['Response']
x=df['Actualmessage']

In [117]:
y

0       1
1       1
2       0
3       1
4       1
5       0
6       1
7       1
8       0
9       0
10      1
11      0
12      0
13      1
14      1
15      0
16      1
17      1
18      1
19      0
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
5542    1
5543    1
5544    1
5545    1
5546    1
5547    0
5548    1
5549    1
5550    1
5551    1
5552    1
5553    1
5554    1
5555    1
5556    1
5557    1
5558    1
5559    1
5560    1
5561    1
5562    1
5563    1
5564    1
5565    1
5566    0
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Response, Length: 5572, dtype: object

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=4)

In [120]:
from sklearn.feature_extraction.text import CountVectorizer

In [121]:
cv=CountVectorizer()

In [124]:
xtraincv=cv.fit_transform(xtrain)

In [125]:
len(cv.get_feature_names())

7222

In [126]:
xtraincv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [127]:
xtestcv=cv.transform(xtest)

In [128]:
xtestcv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [129]:
from sklearn.naive_bayes import MultinomialNB

In [130]:
m=MultinomialNB()

In [131]:
ytrain=ytrain.astype('int')

In [132]:
m.fit(xtraincv,ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [80]:
ypredict=m.predict(xtestcv)

In [81]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [82]:
ytest=ytest.astype('int')

In [83]:
accuracy_score(ypredict,ytest)

0.9796650717703349

In [84]:
c=confusion_matrix(ypredict,ytest)

In [85]:
c

array([[ 213,    7],
       [  27, 1425]], dtype=int64)